# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_amount_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='left_amount',
        ),
    ]
