# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_purchase_left_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount_to_sell',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
